config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get "/blog_post/new" , to: "blog_post#new"
  # get "/blog_post/:id" , to: "blog_post#show" , as: :blog_post
  # get "/blog_post/:id/edit" , to: "blog_post#edit"
  # patch "/blog_post/:id" , to: "blog_post#update"
  # delete "/blog_post/:id" , to: "blog_post#destroy"


  resources :blog_post
  post "/blog_posts" , to: "blog_post#create"

  root "blog_post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  scope :sorted, -> {order(published_at: :desc, updated_at: :desc)}
  scope :draft, -> {where(published_at: nil)}
  scope :published, -> {where("published_at <= ?", Time.current)}
  scope :scheduled, -> {where("published_at > ?", Time.current)}

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post , except: [:index, :new , :create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_params)

    if @blog_post.save
      redirect_to root_path
    else
      render :new , status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_params
    params.require(:blog_post).permit(:title,:body,:published_at)
  end

  def set_blog_post
    if user_signed_in?
      @blog_post = BlogPost.find(params[:id])
    else
      @blog_post = BlogPost.published.find(params[:id])
    end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_post/_form.html.erb
<div>
  <%= form_with model: blog_post, local: true do |form| %>
    <%if form.object.errors.any?%>
      <div>
        <% form.object.errors.full_messages.each do |message|%>
          <div>
            <%=message%>
          </div>
        <%end%>
      </div>
    <%end%>
    <div>
      <%= form.label :title%>
      <%= form.text_field :title%>
    </div>
    <div >
      <%= form.label :body%>
      <%= form.text_area :body%>
    </div>
    <div>
      <%= form.label :published_at%>
      <%= form.datetime_select :published_at, include_blank: true %>
    </div>
    <div>
      <%= form.submit button_name , class: color_for_view%>
    </div>
  <% end %>
</div>

app/views/blog_post/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post, button_name: "Update Post" , color_for_view: "bg-gray-500 text-white p-4 rounded hover:bg-gray-600"} %>

<%= button_to "Delete Post", blog_post_path(@blog_post), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this post?"}, class: "bg-red-500 text-white p-4 rounded hover:bg-red-600"%>

app/views/blog_post/index.html.erb
<h1>My Blog</h1>

<% @blog_posts.each do |blog_post|%>
  <% if blog_post.draft? %>
    <div class= "bg-gray-300 text-white p-4 rounded hover:bg-gray-400">Draft Mode</div>
  <% elsif blog_post.scheduled? %>
    <div class= "bg-blue-300 text-white p-4 rounded hover:bg-blue-400">Scheduled</div>
  <% end %>
  <h2 class="mt-0"><%= link_to blog_post.title, blog_post_path(blog_post.id) %></h2>
  <p><%= blog_post.body %></p>
<% end %>

app/views/blog_post/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post, button_name: "Create Post", color_for_view: "bg-blue-500 text-white p-4 rounded hover:bg-blue-600"} %>

app/views/blog_post/show.html.erb
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>

<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "bg-green-500 text-white p-4 rounded hover:bg-green-600" if user_signed_in? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class ="prose mx-auto">
    <p class ="notice"><%= notice %></p>
    <p class ="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
        <%= link_to "New Blog Post", new_blog_post_path  %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-red-500 text-white p-4 rounded hover:bg-red-600" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>